# Generated by Django 5.1 on 2026-05-12 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=120)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("location", models.CharField(max_length=180)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="daily",
                        max_length=16,
                    ),
                ),
                ("max_pages", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifiers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=150)),
                ("sub_category", models.CharField(blank=True, max_length=150)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=500)),
                ("full_address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=80)),
                ("zip_code", models.CharField(blank=True, max_length=32)),
                ("country", models.CharField(blank=True, default="USA", max_length=80)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("review_count", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("working_hours", models.JSONField(blank=True, default=dict)),
                ("social_media_links", models.JSONField(blank=True, default=list)),
                ("yellowpages_url", models.URLField(max_length=500, unique=True)),
                ("logo_image", models.URLField(blank=True, max_length=500)),
                ("source_keyword", models.CharField(blank=True, max_length=120)),
                ("source_location", models.CharField(blank=True, max_length=180)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="businesses",
                        to="core.notifier",
                    ),
                ),
            ],
            options={
                "ordering": ("-first_seen_at",),
            },
        ),
        migrations.CreateModel(
            name="ScrapeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="started",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("pages_scraped", models.PositiveSmallIntegerField(default=0)),
                ("businesses_found", models.PositiveIntegerField(default=0)),
                ("new_businesses", models.PositiveIntegerField(default=0)),
                ("error_details", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="core.notifier",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsapp_number", models.CharField(blank=True, max_length=32)),
                ("company_name", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="notifier",
            index=models.Index(
                fields=["is_active", "next_run_at"],
                name="core_notifi_is_acti_061193_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notifier",
            index=models.Index(
                fields=["keyword", "location"], name="core_notifi_keyword_41f54b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(fields=["name"], name="core_busine_name_b3e876_idx"),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["category"], name="core_busine_categor_6218c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["city", "state"], name="core_busine_city_d3abc4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="business",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("yellowpages_url__isnull", False),
                    models.Q(("yellowpages_url", ""), _negated=True),
                ),
                name="business_requires_yellowpages_url",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapelog",
            index=models.Index(
                fields=["status", "started_at"], name="core_scrape_status_62badb_idx"
            ),
        ),
    ]
