# Generated by Django 5.1 on 2026-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YellowPagesCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="YellowPagesLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("us", "United States"), ("ca", "Canada")],
                        max_length=2,
                    ),
                ),
                ("geo_search", models.CharField(max_length=180)),
                ("region_code", models.CharField(blank=True, max_length=8)),
            ],
            options={
                "ordering": ("country", "geo_search"),
                "indexes": [
                    models.Index(
                        fields=["country", "geo_search"],
                        name="core_yellow_country_31b226_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "geo_search"),
                        name="uniq_yp_location_country_geo",
                    )
                ],
            },
        ),
    ]
